config/routes.rb
Syfs::Application.routes.draw do
  root :to => "users#dashboard"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :candidate_apps
  resources :employee_applications
  resources :user_blocks

  resources :questions do
    collection do
      get 'answers'
    end
    member do
      get 'answer' => 'questions#answer'
      post 'answer' => 'questions#answer_question', :as => 'answer_this'
      put 'answer' => 'questions#update_answer'
    end
  end
  
  resources :educations
  resources :experiences, only: [:new, :create, :show]
  resources :positions
  resources :schools, only: [:index]
  resources :candidates_concentrations_degrees

  resources :users do
    collection do
      get :login
      get :choose_type
      get :dashboard
    end
  end

  resources :employers do
    collection do
      get :question
      match 'search' => 'employers#search', :via => [:get, :post], :as => :search
    end
  end

  resources :candidates do
    collection do
      get :question
      put :update
    end
  end

  resources :messages do
    collection do
      get :inbox
      get :compose
      get :display
    end
  end

  match "login"     => "users#login",     :as => "login"
  match "dashboard" => "users#dashboard", :as => "dashboard"
  match "profile"   => "users#show",      :as => "profile"
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_sign_in.html.erb
<!--app/views/shared/_sign_in.html.erb-->
<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container" >
					
					<a class="brand" style="font-size:3em;" href="index.html">
						<%= image_tag("sync.png",:size => "100x60") %>SyncSum
					</a>
					<div class="nav-collapse collapse" id="main-menu">
<div style = "float:right; padding-right: 10px; margin-bottom:0px;">
<%= form_for(resource, :as => resource_name, :class => "form-search" ,  :url => session_path(resource_name), :html => { :class => "login" }) do |f| %>
					
					 <%= f.text_field :email, :class=>"span2", :style=>"margin-top:10px; padding:1em",:placeholder => "Email" %>
					 <%= f.password_field :password, :class=>"span2", :style=>"margin-top:10px; padding:1em", :placeholder => "Password" %>

					  <%= f.submit "Sign in", :class =>"button btn btn-primary", :style=>"margin-top:0px" %>
					  <%# link_to "Forgot your password?", new_password_path('user') %>
							
					<% if devise_mapping.rememberable? -%>
					    <div style="color:#ccc;">
						<%= f.check_box :remember_me, :style => "float:left;" %>
						<%= f.label :remember_me, :style => "float:left;" %></div>
					  <% end -%>

					<% end %>
</div>
					</div>
				</div>
			</div>
		</div>

<%#= render "devise/shared/links" %>

app/views/shared/_sign_up.html.erb
<!--app/views/shared/_sign_up.html.erb-->
<%= javascript_include_tag "sign_up_script"%>
		<section id="content">
			<div class="container" >
				<div class="row">
					<div id="mainPageText" class="span6" style=" margin-top:6.5em; padding-left:4em; ">
						
						<h1 style="font-size:40px;"><strong>Job matching. With personality.</strong></h1>
						<br>
						<h2 style="font-size:22px;"><%= image_tag("3.png", :style =>"width:2.5em; opacity:0.25" ) %> Connecting applicants and employers.</h2>
						<h2 style="font-size:22px;"><%= image_tag("2.png", :style =>"width:2.5em; opacity:0.25" ) %> Test your skills. Measure career progress.</h2>
						<h2 style="font-size:22px;"><%= image_tag("1.png", :style =>"width:2.5em; opacity:0.25" ) %> Easy. Smart. Logical.</h2>
					</div>
					<div class="hero-unit span3 pull-right" style="  margin-top:30px; ">
						<h1 style="font-size:2em; padding-bottom:.3em">Sign up for free</h1>

							<div id="signup-user-type" class="btn-group" data-toggle="buttons-radio" style="margin-top:10px; margin-bottom:15px;">
							<%= submit_tag "Candidate", :id=>'candidate-btn', :class=>"btn account-type active", :style=>"color:white;", :onclick=>'candidateSelected()'%>
								<%= submit_tag "Employer", :id=>'employer-btn', :class=> "btn account-type", :style=>"color:#555;", :onclick=>'employerSelected()'%>

						</div>
						
						<div id="candidate-form">
				<form accept-charset="UTF-8" action= "/candidates" class="login" id="new_candidates" method = "post">
							<input id="candidate_user_attributes_email" class="span3" style="margin-top:10px;" name="candidate[user_attributes][email]" placeholder="Email" type="text">
							<input id="candidate_user_attributes_password" class="span3" style="margin-top:10px;" name="candidate[user_attributes][password]" placeholder="Password" type="password">
							<input id="candidate_user_attributes_password_confirmation" style="margin-top:10px;" class="span3" name="candidate[user_attributes][password_confirmation]" placeholder="Confirm Password" type="password">
						<br>
						<button	class="btn btn-large btn-primary button2" name= "commit" type = "submit"  style="margin-top:15px" >Sign Up</button>
				</form>
						</div>
						
						<div id="employer-form" style="display:none;">
				<form accept-charset="UTF-8" action= "/employers" class="login" id="new_employer" method = "post">
							<input id="employer_user_attributes_email" class="span3" style="margin-top:10px;" name="employer[user_attributes][email]" placeholder="Business Email" type="text">
							<input id="employer_user_attributes_password" class="span3" style="margin-top:10px;" name="employer[user_attributes][password]" placeholder="Password" type="password">
							<input id="employer_user_attributes_password_confirmation" style="margin-top:10px;" class="span3" name="employer[user_attributes][password_confirmation]" placeholder="Confirm Password" type="password">
						<br>
						<button	class="btn btn-large btn-primary button2" name= "commit" type = "submit"  style="margin-top:15px" >Sign Up</button>
				</form>
						</div>
						
						
					
						<div><hr></div>
						<h1 style="font-size:1.5em; padding-bottom:.75em">...or sign up with</h1>
						<a href="https://accounts.google.com/AccountChooser?service=lso&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Fopenid2%2Fauth%3Fzt%3DChRiM1hCalc5cmo3QkdFMjdwRDBKMxIfQXA2VVlFeWNLWVVZc2hRVjBpZVpEQXFPbmFabGZRSQ%25E2%2588%2599APsBz4gAAAAAUZY9PLfrCXzIYA_Oy9PG-G_ku8e45-S1%26from_login%3D1%26hl%3Den%26as%3D788f7a6382018abb&btmpl=authsub&hl=en"><%= image_tag("google_plus.png", :style =>"width:40px;" ) %></a>
						<a href="https://api.twitter.com/oauth/authorize?oauth_token=rze7SvdtZLxaDgYOUNTWR2fbuDL5wLxi8wtDMILU"><%= image_tag("twitter.png", :style =>"width:40px;" ) %></a>
						<a href="https://www.linkedin.com/uas/oauth/authorize?oauth_token=68880159-c813-4669-86da-ddf98855624f&state="><%= image_tag("linkedin.png", :style =>"width:40px;" ) %></a>
					</div>
				</div>
			</div>
		</section>