config/routes.rb
Syfs::Application.routes.draw do
  root :to => "users#dashboard"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :candidate_apps
  resources :employee_applications
  resources :user_blocks

  resources :questions do
    collection do
      get 'answers'
    end
    member do
      get 'answer' => 'questions#answer'
      post 'answer' => 'questions#answer_question', :as => 'answer_this'
      put 'answer' => 'questions#update_answer'
    end
  end
  
  resources :educations
  resources :experiences, only: [:new, :create, :show]
  resources :positions
  resources :schools, only: [:index]
  resources :candidates_concentrations_degrees

  resources :users do
    collection do
      get :login
      get :choose_type
      get :dashboard
    end
  end

  resources :employers do
    collection do
      get :question
      match 'search' => 'employers#search', :via => [:get, :post], :as => :search
    end
  end

  resources :candidates do
    collection do
      get :question
      put :update
    end
  end

  resources :messages do
    collection do
      get :inbox
      get :compose
      get :display
    end
  end

  match "login"     => "users#login",     :as => "login"
  match "dashboard" => "users#dashboard", :as => "dashboard"
  match "profile"   => "users#show",      :as => "profile"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer, :question_id

  belongs_to :question
  has_many :preferred_answers
  has_many :employers, :through => :preferred_answer
  has_and_belongs_to_many :candidates
  
  def self.from_question(question)
    where('question_id = ?', question.id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) if can?(:edit, answer) %></td>
    <td><%= link_to 'Destroy', answer, confirm: 'Are you sure?', method: :delete if can?(:destroy, answer) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path if can?(:create, answer) %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= answer.answer %></p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>