config/routes.rb
Syfs::Application.routes.draw do
  root :to => "users#dashboard"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :candidate_apps
  resources :employee_applications
  resources :user_blocks

  resources :questions do
    collection do
      get 'answers'
    end
    member do
      get 'answer' => 'questions#answer'
      post 'answer' => 'questions#answer_question', :as => 'answer_this'
      put 'answer' => 'questions#update_answer'
    end
  end
  
  resources :educations
  resources :experiences, only: [:new, :create, :show]
  resources :positions
  resources :schools, only: [:index]
  resources :candidates_concentrations_degrees

  resources :users do
    collection do
      get :login
      get :choose_type
      get :dashboard
    end
  end

  resources :employers do
    collection do
      get :question
      match 'search' => 'employers#search', :via => [:get, :post], :as => :search
    end
  end

  resources :candidates do
    collection do
      get :question
      put :update
    end
  end

  resources :messages do
    collection do
      get :inbox
      get :compose
      get :display
    end
  end

  match "login"     => "users#login",     :as => "login"
  match "dashboard" => "users#dashboard", :as => "dashboard"
  match "profile"   => "users#show",      :as => "profile"
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  has_many :educations, :dependent => :destroy
  has_many :candidates, :through => :educations
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  # GET /degrees
  # GET /degrees.json
  def index
    @degrees = Degree.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @degrees }
    end
  end

  # GET /degrees/1
  # GET /degrees/1.json
  def show
    @degree = Degree.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @degree }
    end
  end

  # GET /degrees/new
  # GET /degrees/new.json
  def new
    @degree = Degree.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @degree }
    end
  end

  # GET /degrees/1/edit
  def edit
    @degree = Degree.find(params[:id])
  end

  # POST /degrees
  # POST /degrees.json
  def create
    @degree = Degree.new(params[:degree])

    respond_to do |format|
      if @degree.save
        format.html { redirect_to @degree, notice: 'Degree was successfully created.' }
        format.json { render json: @degree, status: :created, location: @degree }
      else
        format.html { render action: "new" }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /degrees/1
  # PUT /degrees/1.json
  def update
    @degree = Degree.find(params[:id])

    respond_to do |format|
      if @degree.update_attributes(params[:degree])
        format.html { redirect_to @degree, notice: 'Degree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degrees/1
  # DELETE /degrees/1.json
  def destroy
    @degree = Degree.find(params[:id])
    @degree.destroy

    respond_to do |format|
      format.html { redirect_to degrees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/views/degrees/_dropdown.html.erb
  <select name="concentration">
  <% @degrees.each do |degree| %>
    <option value="<%= degree.id %>"><%= degree.name %></option>
  <% end %>
  </select>

app/views/degrees/_form.html.erb
<%= form_for(@degree) do |f| %>
  <% if @degree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@degree.errors.count, "error") %> prohibited this degree from being saved:</h2>

      <ul>
      <% @degree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degrees/_name.erb
<%= degree.name %>

app/views/degrees/edit.html.erb
<h1>Editing degree</h1>

<%= render 'form' %>

<%= link_to 'Show', @degree %> |
<%= link_to 'Back', degrees_path %>

app/views/degrees/index.html.erb
<h1>Listing degrees</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @degrees.each do |degree| %>
  <tr>
    <td><%= degree.name %></td>
    <td><%= link_to 'Show', degree %></td>
    <td><%= link_to 'Edit', edit_degree_path(degree) %></td>
    <td><%= link_to 'Destroy', degree, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Degree', new_degree_path %>

app/views/degrees/new.html.erb
<h1>New degree</h1>

<%= render 'form' %>

<%= link_to 'Back', degrees_path %>

app/views/degrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @degree.name %>
</p>


<%= link_to 'Edit', edit_degree_path(@degree) %> |
<%= link_to 'Back', degrees_path %>
<%= link_to 'New', new_degree_path %>