config/routes.rb
Syfs::Application.routes.draw do
  root :to => "users#dashboard"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :candidate_apps
  resources :employee_applications
  resources :user_blocks

  resources :questions do
    collection do
      get 'answers'
    end
    member do
      get 'answer' => 'questions#answer'
      post 'answer' => 'questions#answer_question', :as => 'answer_this'
      put 'answer' => 'questions#update_answer'
    end
  end
  
  resources :educations
  resources :experiences, only: [:new, :create, :show]
  resources :positions
  resources :schools, only: [:index]
  resources :candidates_concentrations_degrees

  resources :users do
    collection do
      get :login
      get :choose_type
      get :dashboard
    end
  end

  resources :employers do
    collection do
      get :question
      match 'search' => 'employers#search', :via => [:get, :post], :as => :search
    end
  end

  resources :candidates do
    collection do
      get :question
      put :update
    end
  end

  resources :messages do
    collection do
      get :inbox
      get :compose
      get :display
    end
  end

  match "login"     => "users#login",     :as => "login"
  match "dashboard" => "users#dashboard", :as => "dashboard"
  match "profile"   => "users#show",      :as => "profile"
end

app/models/user_block.rb
class UserBlock < ActiveRecord::Base
  attr_accessible :blockee, :blocker
end

app/controllers/user_blocks_controller.rb
class UserBlocksController < ApplicationController
  # GET /user_blocks
  # GET /user_blocks.json
  def index
    @user_blocks = UserBlock.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_blocks }
    end
  end

  # GET /user_blocks/1
  # GET /user_blocks/1.json
  def show
    @user_block = UserBlock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_block }
    end
  end

  # GET /user_blocks/new
  # GET /user_blocks/new.json
  def new
    @user_block = UserBlock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_block }
    end
  end

  # GET /user_blocks/1/edit
  def edit
    @user_block = UserBlock.find(params[:id])
  end

  # POST /user_blocks
  # POST /user_blocks.json
  def create
    @user_block = UserBlock.new(params[:user_block])

    respond_to do |format|
      if @user_block.save
        format.html { redirect_to @user_block, notice: 'User block was successfully created.' }
        format.json { render json: @user_block, status: :created, location: @user_block }
      else
        format.html { render action: "new" }
        format.json { render json: @user_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_blocks/1
  # PUT /user_blocks/1.json
  def update
    @user_block = UserBlock.find(params[:id])

    respond_to do |format|
      if @user_block.update_attributes(params[:user_block])
        format.html { redirect_to @user_block, notice: 'User block was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_blocks/1
  # DELETE /user_blocks/1.json
  def destroy
    @user_block = UserBlock.find(params[:id])
    @user_block.destroy

    respond_to do |format|
      format.html { redirect_to user_blocks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_blocks_helper.rb
module UserBlocksHelper
end

app/views/user_blocks/_form.html.erb
<%= form_for(@user_block) do |f| %>
  <% if @user_block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_block.errors.count, "error") %> prohibited this user_block from being saved:</h2>

      <ul>
      <% @user_block.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blocker %><br />
    <%= f.number_field :blocker %>
  </div>
  <div class="field">
    <%= f.label :blockee %><br />
    <%= f.number_field :blockee %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_blocks/edit.html.erb
<h1>Editing user_block</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_block %> |
<%= link_to 'Back', user_blocks_path %>

app/views/user_blocks/index.html.erb
<h1>Listing user_blocks</h1>

<table>
  <tr>
    <th>Blocker</th>
    <th>Blockee</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_blocks.each do |user_block| %>
  <tr>
    <td><%= user_block.blocker %></td>
    <td><%= user_block.blockee %></td>
    <td><%= link_to 'Show', user_block %></td>
    <td><%= link_to 'Edit', edit_user_block_path(user_block) %></td>
    <td><%= link_to 'Destroy', user_block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User block', new_user_block_path %>

app/views/user_blocks/new.html.erb
<h1>New user_block</h1>

<%= render 'form' %>

<%= link_to 'Back', user_blocks_path %>

app/views/user_blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Blocker:</b>
  <%= @user_block.blocker %>
</p>

<p>
  <b>Blockee:</b>
  <%= @user_block.blockee %>
</p>


<%= link_to 'Edit', edit_user_block_path(@user_block) %> |
<%= link_to 'Back', user_blocks_path %>